                    <div id="banner_top" class="pngfix"></div>
            <div id="banner_event" style="background-image: url(8501/img/eventbanner/wild_farm/en.jpg);"  onMouseOver="return escape('<table cellspacing=2 cellpadding=2 valign=middle class=\'tooltipBox\'><tr><td style=\'color:#BA9700; font-weight: bold; font-size:9pt\' colspan=\'2\' nowrap=\'nowrap\'>&iexcl;Las gallinas corretean por el Imperio Romano!</td></tr><tr><td style=\'text-align:left; color:silver; font-weight: bold; font-size:8pt\' nowrap=\'nowrap\'>Final</td><td style=\'padding-left:20px;text-align:right; color:silver; font-weight: bold; font-size:8pt\' nowrap=\'nowrap\'>15.04.2015 23:59</td></tr><tr><td style=\'color:white; font-weight: bold; font-size:8pt\' colspan=\'2\' ><div style=\'width:300px;\'>Poco a poco el tiempo va mejorando en el imperio y las mentes j&oacute;venes comienzan a hacer locuras. Durante la noche, un grupo de gladiadores novatos ha liberado a los animales de todas las granjas de la ciudad para gastar una broma. Ser&aacute;n los luchadores m&aacute;s experimentados quienes tengan que v&eacute;rselas con toda esa volater&iacute;a salvaje. &iquest;Est&aacute;is a la altura para plantar cara a la ira de Berta? &iexcl;A prisa! &iexcl;Salid a buscar a los animales!<br /><br />Vuestro equipo de Gladiatus</div></td></tr></table>');">
                                    <a id="banner_event_link" href="index.php?mod=location&loc=wild_farm&sh=acc8a7e22ab9cb4e2fb94e2f55f05660"></a>
                            </div>

                            <div id="banner_top" class="pngfix"></div>
            <div id="banner_event" style="background-image: url(8501/img/eventbanner/event_costume_party/en.png);"  onMouseOver="return escape('<table cellspacing=2 cellpadding=2 valign=middle class=\'tooltipBox\'><tr><td style=\'color:#BA9700; font-weight: bold; font-size:9pt\' colspan=\'2\' nowrap=\'nowrap\'>Comienza el festival de disfraces</td></tr><tr><td style=\'text-align:left; color:silver; font-weight: bold; font-size:8pt\' nowrap=\'nowrap\'>Final</td><td style=\'padding-left:20px;text-align:right; color:silver; font-weight: bold; font-size:8pt\' nowrap=\'nowrap\'>04.05.2015 23:59</td></tr><tr><td style=\'color:white; font-weight: bold; font-size:8pt\' colspan=\'2\' ><div style=\'width:300px;\'>Se respira ambiente festivo en la ciudad de Roma, pues ha dado comienzo el festival de disfraces. Incluso los gladiadores llevan puestas sus mejores ropas. &iexcl;Pod&eacute;is poneros vuestros disfraces durante el evento y obtener as&iacute; bonificaciones geniales!</div></td></tr></table>');">
                                    <a id="banner_event_link" href="index.php?mod=costumes&sh=acc8a7e22ab9cb4e2fb94e2f55f05660"></a>
                            </div>
