<div id="p2_1_1" style="position:absolute;width:64px;height:64px" onMouseOver="return escape(dd.elements.p2_1_1.tooltip)"><?php echo $p2TEXTimg; ?></div>
<div id="p3_1_1" style="position:absolute;width:32px;height:96px" onMouseOver="return escape(dd.elements.p3_1_1.tooltip)"><?php echo $p3TEXTimg; ?></div>
<div id="p4_1_1" style="position:absolute;width:64px;height:96px" onMouseOver="return escape(dd.elements.p4_1_1.tooltip)"><?php echo $p4TEXTimg; ?></div>
<div id="p6_1_1" style="position:absolute;width:32px;height:32px" onMouseOver="return escape(dd.elements.p6_1_1.tooltip)"><?php echo $p6TEXTimg; ?></div>
<div id="p7_1_1" style="position:absolute;width:32px;height:32px" onMouseOver="return escape(dd.elements.p7_1_1.tooltip)"><?php echo $p7TEXTimg; ?></div>
<div id="p5_1_1" style="position:absolute;width:64px;height:96px" onMouseOver="return escape(dd.elements.p5_1_1.tooltip)"><?php echo $p5TEXTimg; ?></div>
<div id="p9_1_1" style="position:absolute;width:64px;height:64px" onMouseOver="return escape(dd.elements.p9_1_1.tooltip)"><?php echo $p9TEXTimg; ?></div>
<div id="p10_1_1" style="position:absolute;width:64px;height:64px" onMouseOver="return escape(dd.elements.p10_1_1.tooltip)"><?php echo $p10TEXTimg; ?></div>
<div id="p11_1_1" style="position:absolute;width:32px;height:32px" onMouseOver="return escape(dd.elements.p11_1_1.tooltip)"><?php echo $p11TEXTimg; ?></div>